DROP TABLE [dbo].[Times];
DROP TABLE [dbo].[EventTeams];
DROP TABLE [dbo].[AthleteTeams];
DROP TABLE [dbo].[Teams];
DROP TABLE [dbo].[Coaches];
DROP TABLE [dbo].[Events];
DROP TABLE [dbo].[Locations];
DROP TABLE [dbo].[EventTypes];
DROP TABLE [dbo].[Athletes];